### ISSUE TITLE
[FE] 사용자 피드백 개선

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#107]
## ☑️ 진행할 작업

- 사용자 피드백을 개선합니다.

## 📝 TODO

- [ ] : 피드 기록 등록 버튼 안보이는 현상 개선
- [ ] : 웰컴 화면 가운데 정렬
- [ ] : 캐릭터 입 stroke 현상 개선
- [ ] : 구글 아이콘에 회색 네모 박스 개선
- [ ] : 홈에서 글 작성 아이콘이 네비게이팅 바 잘림 현상 개선
- [ ] : 알림 화면 스크롤 개선
- [ ] : 마이페이지 스크롤 개선
- [ ] : 마이페이지 사용자 입력하는 글은 검정색 글씨로 변경
- [ ] : 마이페이지 뒤로가기 버튼 구현
- [ ] : 피드, 기록 사용자 입력 글 검정색 변경 활성화
- [ ] : 팝업 창 비율 개선
