### ISSUE TITLE
[FE] 피드 등록 화면 구현

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#11]
## ☑️ 진행할 작업

- 피드 등록 화면을 구현합니다.

## 📝 TODO
- [ ] : 제목, 여행지, 같이 간 사람, 여행 설명은 글로 작성 할 수있다.
- [ ] : 여행 날짜는 시작 날짜와 끝나는 날짜를 선택 할 수 있다.
- [ ] : 여행 만족도를 선택 할 수 있다.
- [ ] : 썸네일 사진을 클릭하면 썸네일이 보여야 한다.
