### ISSUE TITLE
[FE] 피드 디테일 화면 구현

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#12]
## ☑️ 진행할 작업

- 피드 리스트 클릭시 보이는 디테일 화면 구현

## 📝 TODO

- [ ] : 피드 리스트 클릭 시 디테일 화면으로 넘어간다.
- [ ] : 사진과 기본 정보들이 표시된다.
- [ ] : 카테고리 버튼을 클릭하면, 수정하기, 삭제하기, 공유하기를 선택할 수 있다.
- [ ] : 아래로 내리면 더 자세한 정보를 확인 할 수 있다.
- [ ] : 기록 리스트를 클릭하면 사진이 보이는 형식으로 보인다.
- [ ] : 요약보기는 기본 장소 정보만 보인다.
