### ISSUE TITLE
[FE] 기록  화면 구현

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#13]
## ☑️ 진행할 작업

- 기록을 등록하고, 등록하고 나면 디테일한 기록 내용을 볼 수 있다.
## 📝 TODO

- [ ] : 기록을 등록할 수 있는 첫번째 화면 구현
- [ ] : 첫번째 화면에서 다음을 누르면 두번째 등록할 수있는 화면 구현
- [ ] : 두번째 화면까지 모든 데이터를 입력하면 등록이 가능하다
- [ ] : 데이터를 입력 못했다면 다음 버튼과 등록 버튼이 비활성화된다.
- [ ] : 등록을 다하면 기록 화면이 보인다.
