### ISSUE TITLE
[FE] 마이페이지 화면 구현

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#14]
## ☑️ 진행할 작업

- 마이페이지 화면을 구현합니다.

## 📝 TODO

- [ ] : 마이페이지에서 이미지, 프로필, 닉네임을 변경 할 수 이다.
- [ ] :로그아웃을 하면 로그인페이지로 돌아간다.
- [ ] : 회원탈퇴도 로그인 페이지로 돌아간다.
