### ISSUE TITLE
[FE] 기록 작성 시 이미지 파일 받을 수 있도록 수정

### ISSUE THREAD

**Issue by SeoYeonii** [travel-record/frontend#15]
## ☑️ 진행할 작업
기록 작성 시 이미지 파일 받을 수 있도록 수정합니다.

## 📝 TODO

- [x] : 기록 작성 시 이미지 파일 받을 수 있다.
- [x] : post -> react query 사용해서 컴포넌트와 분리
- [x] : post한 후 받아온 값 제대로 반영되게 수정 (html 형식으로 보냈기 때문에 수정 작업 필요)
- [x] : 썸네일 붙인 뒤 img url 스태틱하게 넣어놓은 값 전 페이지에서 받아온 값으로 수정 -> 다음 이슈에서 수정
- [x] : 이미지 처리 수정 -> img는 따로 aws에 올리고 그 링크를 content에 첨부해서 post
