### ISSUE TITLE
[FE] 공통 컴포넌트 제작

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#16]
## ☑️ 진행할 작업

- 디자인을 보고 필요한 공통 컴포넌트 제작

## 📝 TODO

- [ ] : 버튼 컴포넌트를 제작한다.
- [ ] : 태그 컴포넌트를 제작한다.
- [ ] : textinput 컴포넌트를 제작한다.
