### ISSUE TITLE
[FE] 환경 설정

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#2]
## ☑️ 진행할 작업

- prettier, eslint 환경 설정을 진행한다.
- 절대 경로 환경설정을 진행한다.
- 전역 스타일 환경 설정을 완료한다.

## 📝 TODO

- [x] prettier, eslint 환경 설정
- [x] 절대 경로 환경 설정
- [ ] 전역 스타일 환경 설정
  - [ ] 글로벌 스타일 설정
  - [ ] 폰트, 컬러 설정
  - [ ] theme 설정
  
## ⚙️ 기타
