### ISSUE TITLE
[FE] 피드 수정/삭제 기능

### ISSUE THREAD

**Issue by SeoYeonii** [travel-record/frontend#24]
## ☑️ 진행할 작업
- 피드 수정
- 피드 삭제

## 📝 TODO

- [x] : Feed List -> react-query로 리팩토링
- [x] : Feed Detail -> react-query로 리팩토링

- [x] : select 만들기
- [x] : 피트 select type 만들기
- [x] : modal 만들기
- [x] : 피드 수정
    - [x] : api 구현
    - [x] : select에 붙이기
- [x] : 피드 삭제
    - [x] : api 구현
    - [x] : select에 붙이기
