### ISSUE TITLE
[FE] 기록 댓글 시 알람 확인 기능 및 클릭 시 해당 기록 이동 기능 구현

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#38]
## ☑️ 진행할 작업

- 사용자는 기록에 댓글이 달리면 알림을 받을 수 있고, 알림 클릭 시 해당 기록으로 이동합니다.

## 📝 TODO

- [ ] : 알람버튼을 클릭 시, 알람을 조회 할 수 있다.
- [ ] : 기록에 댓글이 달리면 알람을 받을 수 있다.
- [ ] : 알람 클릭 시 해당 기록으로 이동 할 수 있다.
