### ISSUE TITLE
[FE] 로그인 프로필 설정 화면 구현

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#4]
## ☑️ 진행할 작업

- 신규 회원인 경우 로그인 프로필 설정 화면으로 넘어갈 수 있게, 로그인 프로필 설정 화면을 구현합니다.

## 📝 TODO

- [ ] : 이미지 미리보기 기능 구현
- [ ] : 닉네임 설정 구현
- [ ] : 소개글 구현
- [ ] : 닉네임을 작성하기 전까지, 건너띄기 disabled 처리

## ⚙️ 기타

- 화면 레이아웃이 나오기 전으로 스타일은 포함시키지 않았습니다.
