### ISSUE TITLE
[FE] 마이페이지 좋아요 리스트 구현

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#52]
## ☑️ 진행할 작업

- 마이페이지에서 좋아요를 클릭 시, 좋아요 된 리스트가 있다면 리스트를 보여준다.

## 📝 TODO

- [ ] : 마이페이지 클릭 시, 좋아요 리스트 페이지로 넘어간다
- [ ] : 좋아요가 없을 경우 좋아요 없는 화면을 보여준다.
- [ ] : 좋아요가 있을 경우 리스트를 보여준다.
