### ISSUE TITLE
[FE] 사용자는 기록에 좋아요를 등록/해제할 수 있다.

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#57]
## ☑️ 진행할 작업

- 사용자는 기록에 좋아요를 등록/해제 할 수 있다.

## 📝 TODO

- [ ] : 사용자는 기록을 조회할때, 좋아요가 false면 빈 하트, true면 하트로 표시된다.
- [ ] : 사용자는 빈하트를 누르면 좋아요를 등록할 수있다.
- [ ] : 사용자는 하트를 누르면 좋아요를 해제할 수 있다.
