### ISSUE TITLE
[FE] 알림 타입 별 클릭 시 이동 기능 수정

### ISSUE THREAD

**Issue by yesolyo** [travel-record/frontend#74]
## ☑️ 진행할 작업

- 알림 타입 별 클릭 시 이동 기능 수정합니다.

## 📝 TODO

- [ ] : 좋아요는 해당 기록으로 이동합니다.
- [ ] : 댓글은 해당 댓글로 이동합니다.
- [ ] : 초대는 해당 피드로 이동합니다.
